// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  navigation: dynamic(() => import("./Navigation")),
  rich_text: dynamic(() => import("./RichText")),
};
